[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "super_hard"
version = "0.1.0"
description = "Project using uv package manager"
requires-python = ">=3.10"
dependencies = [
    "mitmproxy"
]

[tool.uv]
python = "3.10.6" 